### ISSUE TITLE
Failed to run with Azure Developer CLI

### ISSUE THREAD

**Issue by v-jiaodi** [Azure-Samples/spring-chatgpt-sample#4]
**Describe the issue:**
When executing `azd up` according to [README.md](https://github.com/Azure-Samples/spring-chatgpt-sample#readme), the error is as follows:

![image](https://github.com/Azure-Samples/spring-chatgpt-sample/assets/80496810/04c582b1-9141-4564-95a6-909b0acc3dfc)

**Repro Steps:**
1. Run `azd auth login`
2. Run `azd config set alpha.springapp on`
3. Run `azd init --template Azure-Samples/spring-chatgpt-sample`
4. Run `azd up`

**Environment:**
- OS: Windows desktop.

**Expected behavior:**
 Run `azd up` can pass.

 @hemarina for notification.

**Comment by yiliuTo** [comment]
@v-jiaodi this error is due to that your subscription doesn' have enough quoto to provision the Azure OpenAI resource, you can check with your subsciption's admin for the quota. Referring to https://learn.microsoft.com/azure/cognitive-services/openai/quotas-limits

**Comment by v-jiaodi** [comment]
@yiliuTo Run `azd up` can pass after synchronizing with this change: https://github.com/Azure-Samples/azure-search-openai-demo/pull/322

**Comment by yiliuTo** [comment]
Thanks @v-jiaodi I will update the AZD template with those changes soon.

**Comment by yiliuTo** [comment]
Close this issue since it has been resolved by #6
